import type { MarketCategory, MarketSourceDefinition } from "./sourceRegistry";

const candidate = (
  key: string,
  canonicalName: string,
  domain: string,
  sourceType: MarketSourceDefinition["sourceType"],
  categories: MarketCategory[],
  geography: MarketSourceDefinition["geography"] = "IN",
): MarketSourceDefinition => ({
  key,
  canonicalName,
  domain,
  sourceType,
  categories,
  geography,
  acquisitionMethod: "OFFICIAL_SITE",
  ingestionEligible: false,
});

/**
 * Expansion universe assembled from category research. These are deliberately
 * non-ingestion-eligible candidates until domain, commercial terms, robots,
 * licensing, price visibility and acquisition method are verified.
 */
export const MARKET_SOURCE_EXPANSION: readonly MarketSourceDefinition[] = [
  candidate("greenlam", "Greenlam Industries", "greenlam.com", "MANUFACTURER", ["boards-laminates-veneers"]),
  candidate("century-laminates", "Century Laminates", "centuryply.com", "MANUFACTURER", ["boards-laminates-veneers"]),
  candidate("merino-laminates", "Merino Laminates", "merinoindia.com", "MANUFACTURER", ["boards-laminates-veneers"]),
  candidate("formica-india", "Formica India", "formica.com", "BRAND", ["boards-laminates-veneers"], "GLOBAL"),
  candidate("wilsonart", "Wilsonart", "wilsonart.com", "BRAND", ["boards-laminates-veneers"], "GLOBAL"),
  candidate("royale-touche", "Royale Touche", "royaletouche.com", "BRAND", ["boards-laminates-veneers"]),
  candidate("virgo-laminates", "Virgo Laminates", "virgolaminates.com", "MANUFACTURER", ["boards-laminates-veneers"]),
  candidate("stylam", "Stylam Industries", "stylam.com", "MANUFACTURER", ["boards-laminates-veneers"]),
  candidate("decolam", "Decolam", "decolam.com", "BRAND", ["boards-laminates-veneers"]),
  candidate("euro-pratik", "Euro Pratik", "europratik.com", "BRAND", ["boards-laminates-veneers"], "GLOBAL"),
  candidate("royale-laminates", "Royale Touche Laminates", "royaletouche.com", "BRAND", ["boards-laminates-veneers"]),
  candidate("kitply", "Kitply", "kitply.com", "MANUFACTURER", ["boards-laminates-veneers"]),
  candidate("duroply", "Duroply", "duroply.in", "MANUFACTURER", ["boards-laminates-veneers"]),
  candidate("sarda-plywood", "Sarda Plywood", "sardaplywood.com", "MANUFACTURER", ["boards-laminates-veneers"]),
  candidate("national-plywood", "National Plywood", "nationalply.com", "MANUFACTURER", ["boards-laminates-veneers"]),
  candidate("mangalam-timber", "Mangalam Timber", "mangalamtimber.com", "MANUFACTURER", ["boards-laminates-veneers"]),
  candidate("rushil-decor", "Rushil Decor", "rushil.com", "MANUFACTURER", ["boards-laminates-veneers"]),
  candidate("greenpanel-mdf", "Greenpanel MDF", "greenpanel.com", "MANUFACTURER", ["boards-laminates-veneers"]),
  candidate("actiontesa", "Action TESA", "actiontesa.com", "MANUFACTURER", ["boards-laminates-veneers"]),
  candidate("merino-boards", "Merino Boards", "merinoindia.com", "MANUFACTURER", ["boards-laminates-veneers"]),
  candidate("sainik", "Sainik", "centuryply.com", "BRAND", ["boards-laminates-veneers"]),

  candidate("dorma", "dormakaba India", "dormakaba.com", "MANUFACTURER", ["hardware", "doors-glass"], "GLOBAL"),
  candidate("geze", "GEZE India", "geze.in", "MANUFACTURER", ["hardware", "doors-glass"]),
  candidate("assa-abloy", "ASSA ABLOY India", "assaabloy.com", "MANUFACTURER", ["hardware", "doors-glass"], "GLOBAL"),
  candidate("yale", "Yale India", "yalehome.com", "BRAND", ["hardware", "fans-smart-home"], "GLOBAL"),
  candidate("dorset", "Dorset", "dorsetindia.com", "MANUFACTURER", ["hardware", "doors-glass"]),
  candidate("ozone", "Ozone", "ozone-india.com", "MANUFACTURER", ["hardware", "doors-glass"]),
  candidate("link-lock", "Link Locks", "linklocks.in", "MANUFACTURER", ["hardware"]),
  candidate("godrej-locks", "Godrej Locks", "godrejlocks.com", "BRAND", ["hardware"]),
  candidate("d-line", "d line", "dline.com", "MANUFACTURER", ["hardware"], "GLOBAL"),
  candidate("grass", "Grass", "grass.eu", "MANUFACTURER", ["hardware"], "GLOBAL"),
  candidate("salice", "Salice", "salice.com", "MANUFACTURER", ["hardware"], "GLOBAL"),
  candidate("ferrari-italia", "FERRARI Components", "ferrari-components.com", "MANUFACTURER", ["hardware"], "GLOBAL"),
  candidate("kessebohmer", "Kesseböhmer", "kesseboehmer.com", "MANUFACTURER", ["hardware"], "GLOBAL"),
  candidate("peka", "Peka", "peka-system.ch", "MANUFACTURER", ["hardware"], "GLOBAL"),
  candidate("hafele", "Häfele", "hafele.com", "MANUFACTURER", ["hardware", "lighting"], "GLOBAL"),
  candidate("hettich-global", "Hettich", "hettich.com", "MANUFACTURER", ["hardware"], "GLOBAL"),

  candidate("astral", "Astral Pipes", "astralpipes.com", "MANUFACTURER", ["bathroom-sanitary-plumbing"]),
  candidate("supreme", "Supreme Industries", "supreme.co.in", "MANUFACTURER", ["bathroom-sanitary-plumbing"]),
  candidate("ashirvad", "Ashirvad Pipes", "ashirvad.com", "MANUFACTURER", ["bathroom-sanitary-plumbing"]),
  candidate("finolex-pipes", "Finolex Industries", "finolexpipes.com", "MANUFACTURER", ["bathroom-sanitary-plumbing"]),
  candidate("prince-pipes", "Prince Pipes", "princepipes.com", "MANUFACTURER", ["bathroom-sanitary-plumbing"]),
  candidate("ajay-pipes", "Ajay Pipes", "ajaypipes.com", "MANUFACTURER", ["bathroom-sanitary-plumbing"]),
  candidate("apollo-pipes", "Apollo Pipes", "apollopipes.com", "MANUFACTURER", ["bathroom-sanitary-plumbing"]),
  candidate("kessel", "Kessel", "kessel.com", "MANUFACTURER", ["bathroom-sanitary-plumbing"], "GLOBAL"),
  candidate("geberit", "Geberit India", "geberit.in", "MANUFACTURER", ["bathroom-sanitary-plumbing"]),
  candidate("geberit-global", "Geberit", "geberit.com", "MANUFACTURER", ["bathroom-sanitary-plumbing"], "GLOBAL"),
  candidate("grohe-global", "GROHE", "grohe.com", "BRAND", ["bathroom-sanitary-plumbing"], "GLOBAL"),
  candidate("hansgrohe", "hansgrohe India", "hansgrohe.in", "BRAND", ["bathroom-sanitary-plumbing"]),
  candidate("kohler-global", "Kohler", "kohler.com", "BRAND", ["bathroom-sanitary-plumbing"], "GLOBAL"),
  candidate("villeroy-boch", "Villeroy & Boch", "villeroy-boch.com", "BRAND", ["bathroom-sanitary-plumbing"], "GLOBAL"),
  candidate("ideal-standard", "Ideal Standard", "idealstandard.com", "BRAND", ["bathroom-sanitary-plumbing"], "GLOBAL"),
  candidate("hansgrohe-global", "Hansgrohe", "hansgrohe.com", "BRAND", ["bathroom-sanitary-plumbing"], "GLOBAL"),
  candidate("roca-global", "Roca", "roca.com", "BRAND", ["bathroom-sanitary-plumbing"], "GLOBAL"),
  candidate("jaquar-global", "Jaquar", "jaquar.com", "BRAND", ["bathroom-sanitary-plumbing"], "GLOBAL"),

  candidate("pidilite", "Pidilite Industries", "pidilite.com", "MANUFACTURER", ["hardware", "paint-wall-finishes"]),
  candidate("dr-fixit", "Dr. Fixit", "drfixit.co.in", "BRAND", ["paint-wall-finishes"]),
  candidate("sika-india", "Sika India", "sika.com", "MANUFACTURER", ["paint-wall-finishes"], "GLOBAL"),
  candidate("fosroc", "Fosroc India", "fosroc.com", "MANUFACTURER", ["paint-wall-finishes"], "GLOBAL"),
  candidate("myk-arko", "MYK Arment", "mykarment.com", "MANUFACTURER", ["paint-wall-finishes"]),
  candidate("jk-cement", "JK Cement", "jkcement.com", "MANUFACTURER", ["paint-wall-finishes"]),
  candidate("birla-white", "Birla White", "adityabirla.com", "BRAND", ["paint-wall-finishes"]),
  candidate("jk-white", "JK White", "jkcement.com", "BRAND", ["paint-wall-finishes"]),
  candidate("oikos", "Oikos India", "oikos-paint.com", "BRAND", ["paint-wall-finishes"], "GLOBAL"),
  candidate("sheenlac", "Sheenlac", "sheenlac.com", "MANUFACTURER", ["paint-wall-finishes"]),
  candidate("wood-finishes", "Asian Paints Wood Finishes", "asianpaints.com", "BRAND", ["paint-wall-finishes"]),

  candidate("anchor", "Anchor by Panasonic", "panasonic.com", "BRAND", ["electrical", "fans-smart-home"], "GLOBAL"),
  candidate("legrand-global", "Legrand", "legrand.com", "MANUFACTURER", ["electrical", "fans-smart-home"], "GLOBAL"),
  candidate("schneider-global", "Schneider Electric", "se.com", "MANUFACTURER", ["electrical", "fans-smart-home"], "GLOBAL"),
  candidate("abb", "ABB India", "abb.com", "MANUFACTURER", ["electrical", "fans-smart-home"], "GLOBAL"),
  candidate("siemens", "Siemens", "siemens.com", "MANUFACTURER", ["electrical", "fans-smart-home"], "GLOBAL"),
  candidate("ls-electric", "LS Electric", "ls-electric.com", "MANUFACTURER", ["electrical"], "GLOBAL"),
  candidate("havells-global", "Havells", "havells.com", "MANUFACTURER", ["electrical", "lighting"]),
  candidate("polycab-global", "Polycab", "polycab.com", "MANUFACTURER", ["electrical"]),
  candidate("finolex-cables", "Finolex Cables", "finolex.com", "MANUFACTURER", ["electrical"]),
  candidate("rr-kabel", "RR Kabel", "rrkabel.com", "MANUFACTURER", ["electrical"]),
  candidate("kei", "KEI Industries", "kei-ind.com", "MANUFACTURER", ["electrical"]),
  candidate("syska", "Syska", "syska.co.in", "BRAND", ["lighting", "fans-smart-home"]),
  candidate("wipro-consumer", "Wipro Consumer Lighting", "wiproconsumercare.com", "BRAND", ["lighting"]),
  candidate("bajaj-lighting", "Bajaj Electricals", "bajajelectricals.com", "MANUFACTURER", ["lighting", "fans-smart-home"]),
  candidate("orient-electric-global", "Orient Electric", "orientelectric.com", "MANUFACTURER", ["lighting", "fans-smart-home"]),
  candidate("atomberg-global", "Atomberg", "atomberg.com", "MANUFACTURER", ["fans-smart-home"]),
  candidate("usha", "Usha", "usha.com", "BRAND", ["fans-smart-home"]),
  candidate("orpat", "Orpat", "orpatgroup.com", "BRAND", ["electrical"]),

  candidate("somany-global", "Somany Ceramics", "somanyceramics.com", "MANUFACTURER", ["tiles-surfaces"]),
  candidate("kajaria-global", "Kajaria", "kajariaceramics.com", "MANUFACTURER", ["tiles-surfaces"]),
  candidate("johnson-global", "H&R Johnson", "hrjohnson.com", "MANUFACTURER", ["tiles-surfaces"]),
  candidate("orientbell-global", "Orientbell Tiles", "orientbell.com", "MANUFACTURER", ["tiles-surfaces"]),
  candidate("vitrified-tiles", "Varmora", "varmoragranito.com", "MANUFACTURER", ["tiles-surfaces"]),
  candidate("agl-global", "Asian Granito", "aglasiangranito.com", "MANUFACTURER", ["tiles-surfaces"]),
  candidate("nitco-global", "NITCO", "nitco.in", "MANUFACTURER", ["tiles-surfaces"]),
  candidate("simpolo-global", "Simpolo", "simpolo.net", "MANUFACTURER", ["tiles-surfaces"]),
  candidate("qutone-global", "Qutone", "qutoneceramic.com", "MANUFACTURER", ["tiles-surfaces"]),
  candidate("rak-global", "RAK Ceramics", "rakceramics.com", "MANUFACTURER", ["tiles-surfaces"], "GLOBAL"),
  candidate("dune-ceramics", "Dune Ceramics", "duneceramics.com", "MANUFACTURER", ["tiles-surfaces"], "GLOBAL"),
  candidate("marazzi", "Marazzi", "marazzi.com", "BRAND", ["tiles-surfaces"], "GLOBAL"),
  candidate("atlas-concorde", "Atlas Concorde", "atlasconcorde.com", "BRAND", ["tiles-surfaces"], "GLOBAL"),
  candidate("porcelanosa", "Porcelanosa", "porcelanosa.com", "BRAND", ["tiles-surfaces"], "GLOBAL"),
  candidate("orientbell-bath", "Orientbell", "orientbell.com", "MANUFACTURER", ["tiles-surfaces"]),

  candidate("saint-gobain-glass", "Saint-Gobain Glass India", "saint-gobain-glass.com", "MANUFACTURER", ["doors-glass"], "GLOBAL"),
  candidate("modiguard", "Modiguard", "modiguard.com", "MANUFACTURER", ["doors-glass"]),
  candidate("asahi-glass", "AGC / Asahi Glass", "agc.com", "MANUFACTURER", ["doors-glass"], "GLOBAL"),
  candidate("guardian-glass", "Guardian Glass", "guardianglass.com", "MANUFACTURER", ["doors-glass"], "GLOBAL"),
  candidate("toughened-glass", "AIS Glass", "aisglass.com", "MANUFACTURER", ["doors-glass"]),
  candidate("fenesta", "Fenesta", "fenesta.com", "MANUFACTURER", ["doors-glass"]),
  candidate("alupure", "Alupure", "alupure.com", "MANUFACTURER", ["doors-glass"]),
  candidate("lingel", "Lingel Windows", "lingelwindows.com", "MANUFACTURER", ["doors-glass"]),
  candidate("prominance", "Prominance", "prominance.com", "MANUFACTURER", ["doors-glass"]),
  candidate("deceuninck", "Deceuninck", "deceuninck.com", "MANUFACTURER", ["doors-glass"], "GLOBAL"),

  candidate("hunter-douglas", "Hunter Douglas", "hunterdouglas.com", "MANUFACTURER", ["curtains-blinds", "ceiling-acoustic"], "GLOBAL"),
  candidate("vista-blinds", "Vista Blinds", "vistablinds.com", "SPECIALIST", ["curtains-blinds"], "GLOBAL"),
  candidate("ddecor", "D'Decor", "ddecor.com", "BRAND", ["curtains-blinds", "soft-furnishings-decor"]),
  candidate("bombay-dyeing", "Bombay Dyeing", "bombaydyeing.com", "BRAND", ["soft-furnishings-decor"]),
  candidate("spaces", "Spaces", "spaces.in", "BRAND", ["curtains-blinds", "soft-furnishings-decor"]),
  candidate("portico", "Portico New York", "porticolifestyle.com", "BRAND", ["soft-furnishings-decor"]),
  candidate("jaipur-rugs", "Jaipur Rugs", "jaipurrugs.com", "BRAND", ["flooring", "soft-furnishings-decor"]),
  candidate("obeetee", "Oberoi / Obeetee", "obeetee.com", "BRAND", ["flooring", "soft-furnishings-decor"]),
  candidate("carpet-cellar", "Carpet Cellar", "carpetcellar.com", "SPECIALIST", ["flooring", "soft-furnishings-decor"], "GLOBAL"),
  candidate("welspun", "Welspun Living", "welspunliving.com", "BRAND", ["soft-furnishings-decor"]),
  candidate("pure-home", "Pure Home + Living", "purehomeandliving.com", "RETAILER", ["soft-furnishings-decor"]),
  candidate("ellementry", "Ellementry", "ellementry.com", "RETAILER", ["soft-furnishings-decor", "furniture"]),
  candidate("home-town", "HomeTown", "hometown.in", "RETAILER", ["furniture", "soft-furnishings-decor"]),
  candidate("homecentre-global", "Home Centre", "homecentre.com", "RETAILER", ["furniture", "soft-furnishings-decor"], "GLOBAL"),

  candidate("featherlite", "Featherlite", "featherlitefurniture.com", "MANUFACTURER", ["furniture"]),
  candidate("haworth", "Haworth", "haworth.com", "MANUFACTURER", ["furniture"], "GLOBAL"),
  candidate("steelcase", "Steelcase", "steelcase.com", "MANUFACTURER", ["furniture"], "GLOBAL"),
  candidate("herman-miller", "Herman Miller", "hermanmiller.com", "MANUFACTURER", ["furniture"], "GLOBAL"),
  candidate("durian-global", "Durian", "durian.in", "RETAILER", ["furniture"]),
  candidate("royaloak-global", "Royaloak", "royaloakindia.com", "RETAILER", ["furniture"]),
  candidate("pepperfry-global", "Pepperfry", "pepperfry.com", "RETAILER", ["furniture"]),
  candidate("urban-ladder-global", "Urban Ladder", "urbanladder.com", "RETAILER", ["furniture"]),
  candidate("woodenstreet-global", "WoodenStreet", "woodenstreet.com", "RETAILER", ["furniture"]),
  candidate("wakefit-global", "Wakefit", "wakefit.co", "RETAILER", ["furniture", "soft-furnishings-decor"]),
  candidate("sleepyhead", "Sleepyhead", "mysleepyhead.com", "BRAND", ["soft-furnishings-decor"]),
  candidate("duroflex-global", "Duroflex", "duroflexworld.com", "BRAND", ["soft-furnishings-decor"]),
  candidate("sleep-company-global", "The Sleep Company", "thesleepcompany.in", "BRAND", ["soft-furnishings-decor"]),
  candidate("nilkamal-global", "Nilkamal", "nilkamal.com", "MANUFACTURER", ["furniture", "outdoor"]),
  candidate("pepperfry-market", "Pepperfry Marketplace", "pepperfry.com", "MARKETPLACE", ["furniture", "lighting", "soft-furnishings-decor"]),

  candidate("bosch-global", "Bosch Home", "bosch-home.com", "BRAND", ["appliances"], "GLOBAL"),
  candidate("siemens-home", "Siemens Home", "siemens-home.bsh-group.com", "BRAND", ["appliances"], "GLOBAL"),
  candidate("electrolux", "Electrolux", "electrolux.com", "BRAND", ["appliances"], "GLOBAL"),
  candidate("whirlpool-global", "Whirlpool", "whirlpool.com", "BRAND", ["appliances"], "GLOBAL"),
  candidate("haier-global", "Haier", "haier.com", "BRAND", ["appliances"], "GLOBAL"),
  candidate("lg-global", "LG", "lg.com", "BRAND", ["appliances", "fans-smart-home"], "GLOBAL"),
  candidate("samsung-global", "Samsung", "samsung.com", "BRAND", ["appliances", "fans-smart-home"], "GLOBAL"),
  candidate("faber-global", "Faber", "faberonline.com", "BRAND", ["appliances"], "GLOBAL"),
  candidate("elica-global", "Elica", "elica.com", "BRAND", ["appliances"], "GLOBAL"),
  candidate("franke-global", "Franke", "franke.com", "MANUFACTURER", ["kitchens-cabinetry", "appliances"], "GLOBAL"),
  candidate("kaff-global", "KAFF", "kaff.in", "BRAND", ["appliances"]),
  candidate("glen-global", "Glen", "glenindia.com", "BRAND", ["appliances"]),

  candidate("livspace-global", "Livspace", "livspace.com", "DESIGNER", ["designers-services"]),
  candidate("homelane-global", "HomeLane", "homelane.com", "DESIGNER", ["designers-services"]),
  candidate("designcafe-global", "DesignCafe", "designcafe.com", "DESIGNER", ["designers-services"]),
  candidate("bonito-global", "Bonito Designs", "bonito.in", "DESIGNER", ["designers-services"]),
  candidate("foyr", "Foyr", "foyr.com", "SERVICE", ["designers-services"], "GLOBAL"),
  candidate("magicbricks-interiors", "MagicBricks Interiors", "magicbricks.com", "SERVICE", ["designers-services"]),
  candidate("nobroker-interiors", "NoBroker Interiors", "nobroker.in", "SERVICE", ["designers-services"]),
  candidate("asian-paints-beauty", "Asian Paints Beautiful Homes", "asianpaints.com", "SERVICE", ["designers-services", "paint-wall-finishes"]),
];
