-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'PRICE_DROP';
ALTER TYPE "NotificationType" ADD VALUE 'BETTER_ALTERNATIVE_FOUND';
ALTER TYPE "NotificationType" ADD VALUE 'BUDGET_EXCEEDED';
ALTER TYPE "NotificationType" ADD VALUE 'DESIGN_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'WALKTHROUGH_READY';
